
POST http://localhost:8080/createUser HTTP/1.1
Content-Type: application/json

{
		"data_type": "database",
		"name": "John",
		"age": 25,
		"address": {
			"street": "123 Main St",
			"city": "Anytown"
		},
		"phones": ["123-4567", "234-5678"]
}